version: '3'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql/

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      MYSQL_HOST: db
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      SELENIUM_DRIVER_URL: "http://selenium_chrome:4444/wd/hub"
    volumes:
      - .:/portfolio_rails
      # https://qiita.com/shotat/items/57d049793605ffc20135
      - bundle:/bundle
      - /portfolio_rails/log
      - /portfolio_rails/tmp
    ports:
      - "3000:3000"
    depends_on:
      - db
      - chrome
    networks:
      - default
    stdin_open: true
    tty: true
    command: bundle exec rails server -b 0.0.0.0

  chrome:
    image: selenium/standalone-chrome:latest
    ports:
    - 4444:4444

volumes:
  mysql_data:
    driver: local

  bundle:
    driver: local



