version: 2.1
jobs:
  rspec:
    working_directory: ~/portfolio_rails
    docker:
      - image: cimg/ruby:2.7.3
    resource_class: small
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
      - run: #環境変数の設定
          name: Setup environment variable
          command: |
            echo "export COMPOSE_FILE=docker-compose.ci.yml" >> $BASH_ENV
      - run:
          # CI実行の高速化のためにgemのinstall先とキャッシュの格納先を vendor/bundle 配下に修正
          name: Configure Bundler
          command: |
            gem install bundler:1.17.2
            bundle check --path=vendor/bundle || bundle install --path vendor/bundle --clean --jobs 4 --retry 3
      - restore_cache:
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
          paths:
            - ./vendor/bundle
      - run: #circle CI CLIではsetup_remote_dockerを使用するとエラー発生
          name: Start containers and verify it is working
          command: |
            set -x
            docker-compose up --build -d
            docker exec portfolio_rails_app curl -4 --retry 10 --retry-delay 3 --retry-connrefused http://localhost:3000
            docker-compose stop
      - run:
          name: yarn install & webpacker compile
          command: |
            set -x
            docker-compose run --rm web yarn install --cache-files
            docker-compose run --rm web bundle exec bin/webpack
      - run:
          name: Setup database
          command: |
            set -x
            docker-compose up -d
            docker-compose run web bundle exec rails db:create
            docker-compose run web bundle exec rails db:migrate
            docker-compose run web bundle exec rails db:seed_fu
      - run:
          name: Run rspec
          command: docker-compose run web bundle exec rspec

  rubocop:
    working_directory: ~/portfolio_rails
    docker:
      - image: cimg/ruby:2.7.3
    resource_class: small
    steps:
      - checkout
      - run: gem install bundler:1.17.2
      - restore_cache:
          keys:
            - gemfiles-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - gemfiles-{{ .Branch }}-
            - gemfiles-master-
      - run: bundle config --local path vendor/bundle
      - run:
          name: bundle install
          command: bundle check || bundle install --jobs=8 --clean
      - run:
          name: Run rubocop
          command: bundle exec rubocop --parallel
      - save_cache:
          key: gemfiles-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

orbs:
  build-tools: circleci/build-tools@2.6.3
  jq: circleci/jq@1.9.1
workflows:
  version: 2.1
  build:
    jobs:
      - rspec
      - rubocop


